language: php
php:
    - 5.5
services:
    - memcached
before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev
    - memcached -p 11211 -d
script:
    - ./vendor/bin/phpunit -c test/phpunit.xml
